### ISSUE TITLE
Convert the other way?

### ISSUE THREAD

**Issue by fruiz500** [dchest/ed2curve-js#2]
I would like to generate a curve25519 keypair, and then optionally obtain the pair, secret key, or public key associated to that pair in curve ed25519. This is because my application is primarily for encryption, and then optionally for signatures.

Can this be done starting from your code?

**Comment by dchest** [comment]
Converting the other way possible, but you won't be able to use such keys for signing without modifications to signing code, because Ed25519 have a sign bit, so you'll need to store it somewhere. For example, Signal stores sign bit in signature (https://moderncrypto.org/mail-archive/curves/2014/000205.html).

So, the best way to do what you want to do is to generate Ed25519 key pair and then use it for encryption (by converting to Curve25519 key) and, optionally, for signing (directly).

**Comment by dchest** [comment]
See also issue #1
