### ISSUE TITLE
Any updates on the security proof of doing this?

### ISSUE THREAD

**Issue by VogtAI** [dchest/ed2curve-js#5]

**Comment by dchest** [comment]
I'm not aware of any new developments on this topic. Perhaps, the best way to go is to ask in one of the cryptographic forums, such as [crypto.stackexchange](https://crypto.stackexchange.com/questions/3260/using-same-keypair-for-diffie-hellman-and-signing/3311#3311) linked from the README in *"Note that there's currently [no proof](https://crypto.stackexchange.com/questions/3260/using-same-keypair-for-diffie-hellman-and-signing/3311#3311) that this is safe to do"* sentence rather than on a bug tracker of this implementation.

**Comment by jcushman** [comment]
@dchest, this paper might be relevant, though I don't understand what limitations come with the proof:

Erik Thormarker, On using the same key pair for Ed25519 and an X25519 based KEM, https://eprint.iacr.org/2021/509.pdf
